### ISSUE TITLE
make chokes on invalid css (which is totally valid)

### ISSUE THREAD

**Issue by chris-jan-trapp** [programmfabrik/easydb-example-plugin#1]
Make dies with:

````bash
mkdir -p build/webfrontend/
cat src/webfrontend/example-plugin.scss | sass --stdin > build/webfrontend/example-plugin.css || ( rm -f build/webfrontend/example-plugin.css ; false )
Error: Invalid CSS after "10px": expected expression (e.g. 1px, bold), was ";"
        on line 2 of standard input
  Use --trace for backtrace.
make: *** [easydb-library/tools/base-plugins.make:20: build/webfrontend/example-plugin.css] Error 1
````

This is weird, as the css that is mentioned is actually valid. The full stack trace produced by sass looks like this:

````bash
$ cat src/webfrontend/example-plugin.scss | sass --stdin --trace > build/webfrontend/example-plugin.css
Traceback (most recent call last):
	27: from /usr/bin/sass:8:in `<main>'
	26: from /usr/lib/ruby/vendor_ruby/sass/exec/base.rb:18:in `parse!'
	25: from /usr/lib/ruby/vendor_ruby/sass/exec/base.rb:50:in `parse'
	24: from /usr/lib/ruby/vendor_ruby/sass/exec/sass_scss.rb:63:in `process_result'
	23: from /usr/lib/ruby/vendor_ruby/sass/exec/sass_scss.rb:392:in `run'
	22: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:290:in `render'
	21: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:417:in `_to_tree'
	20: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:557:in `append_children'
	19: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:557:in `each'
	18: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:558:in `block in append_children'
	17: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:541:in `build_tree'
	16: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:541:in `each'
	15: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:548:in `block in build_tree'
	14: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:557:in `append_children'
	13: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:557:in `each'
	12: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:558:in `block in append_children'
	11: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:539:in `build_tree'
	10: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:666:in `parse_line'
	 9: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:707:in `parse_property_or_rule'
	 8: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:745:in `parse_property'
	 7: from /usr/lib/ruby/vendor_ruby/sass/engine.rb:1169:in `parse_script'
	 6: from /usr/lib/ruby/vendor_ruby/sass/script.rb:27:in `parse'
	 5: from /usr/lib/ruby/vendor_ruby/sass/script/parser.rb:228:in `parse'
	 4: from /usr/lib/ruby/vendor_ruby/sass/script/parser.rb:69:in `parse'
	 3: from /usr/lib/ruby/vendor_ruby/sass/script/parser.rb:897:in `assert_done'
	 2: from /usr/lib/ruby/vendor_ruby/sass/script/lexer.rb:240:in `expected!'
	 1: from /usr/lib/ruby/vendor_ruby/sass/scss/parser.rb:1308:in `expected'
(sass):2: Invalid CSS after "10px": expected expression (e.g. 1px, bold), was ";" (Sass::SyntaxError)
````

**Comment by KlausThornProgrammfabrik** [comment]
Sorry to let you hanging here. If this is still an issue, please write to support@programmfabrik.de

To avoid this in the future we will disables issues on github, as we use our internal issue tracker.
